services:
  # --- DEVELOPMENT SERVICES ---
  mongodb-dev:
    image: mongo:latest
    profiles: ["dev", "dev-server"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    command: mongod --quiet

  backend-dev:
    build: ./server
    profiles: ["dev", "dev-server"]
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - ./server:/server
    environment:
      PORT: 5000
      NODE_ENV: ${NODE_ENV_DEV}
      MONGODB_URI: ${MONGO_URI_DEV}
      ENERGY_API_TOKEN: ${ENERGY_API_TOKEN_ENV}
      JWT_SECRET: ${JWT_SECRET_DEV}

  frontend-dev:
    build:
      context: ./client
      target: development
    profiles: ["dev", "dev-client"]
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      VITE_PORT: 5173
      VITE_API_URL: ${API_URL_DEV}

  # --- DEPLOYMENT SERVICES NOT USED AT THE MOMENT ---
  backend-dep:
    build: ./server
    profiles: ["dep"]
    environment:
      PORT: 5000
      NODE_ENV: ${NODE_ENV_DEP}
      MONGODB_URI: ${MONGO_URI_DEP}
      JWT_SECRET: ${JWT_SECRET_DEP}

  frontend-dep:
    build:
      context: ./client
      target: production
    profiles: ["dep"]
    ports:
      - "80:80"
    environment:
      VITE_API_URL: ${API_URL_DEP}

volumes:
  mongodb_data: